### ISSUE TITLE
Bulid fails if locale is not UTF-8

### ISSUE THREAD

**Issue by arvedarved** [michael-lazar/mailcap_fix#1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 7, in <module>
    long_description=open('README.rst').read(),
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2029: ordinal not in range(128)

Probably needs some sys.setdefaultencoding('utf8') somewhere in setup.py

**Comment by michael-lazar** [comment]
Merged in #2
